name: Build & Push TKT Dev Containers (Base)

permissions:
  packages: write
  contents: read

on:
  workflow_dispatch:   # manual trigger only

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro: [arch, debian, gentoo-openrc, gentoo-systemd, mint, nixos, fedora, popos, slackware, suse, ubuntu, void]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push base image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.distro }}-base.Dockerfile
          push: true                    # Always push on manual run
          tags: ghcr.io/the-kernel-toolkit/tkt-${{ matrix.distro }}-dev:latest
