name: Update & Push TKT Dev Containers

permissions:
  packages: write
  contents: read

on:
  workflow_dispatch:   # manual trigger
  schedule:
    - cron: '0 0 4 * *'  # every week (4 AM UTC, adjust as needed)

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro: [arch, debian, gentoo-openrc, gentoo-systemd, mint, nixos, fedora, popos, slackware, suse, ubuntu, void]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push updated containers
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.distro }}-updater.Dockerfile
          push: true
          tags: ghcr.io/the-kernel-toolkit/tkt-${{ matrix.distro }}-dev:latest
